name: Notify Forks

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to fork
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Ruben0304/PlayUpBackend
          event-type: push_event
          client-payload: '{"ref": "${{ github.ref }}"}'
      - name: Sincronizar con upstream
        run: |
          git remote add upstream https://github.com/PlayUpOrg/PlayUpBackend.git
          git fetch upstream main
          git checkout main
          
          # Crear una rama temporal para la fusión
          git checkout -b temp-merge-branch
          
          # Fusionar excluyendo archivos de workflow
          git merge -X ours --no-commit upstream/main
          git reset HEAD .github/workflows/
          git checkout -- .github/workflows/
          
          # Confirmar y enviar los cambios
          git commit -m "Merge upstream changes excluding workflows"
          git checkout main
          git merge temp-merge-branch
          git push origin main